name: pro_video_editor_example
description: "Demonstrates how to use the pro_video_editor plugin."
publish_to: 'none'

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  pro_video_editor: ^1.15.0

  intl: ^0.20.1
  cupertino_icons: ^1.0.8

  pro_image_editor: ^12.0.11

  google_fonts: ^6.3.2
  flutter_colorpicker: ^1.1.0
  file_picker: ^10.2.1
  mime: ^2.0.0
  wav: 1.5.0

  path_provider: ^2.1.5
  video_player: ^2.9.3
  audioplayers: ^5.2.1

  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  image_picker: ^1.2.2
  firebase_core: ^4.8.0
  firebase_auth: ^6.5.0
  cloud_firestore: ^6.4.0
  firebase_storage: ^13.4.0
  path: ^1.9.1

dev_dependencies:
  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/tests/