// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs9shlH6BKBjV5kH7DbM6zGSJQN7Xr9go',
    appId: '1:259944737321:web:216f33ac761ccfc94bca38',
    messagingSenderId: '259944737321',
    projectId: 'pro-video-editor-5c91d',
    authDomain: 'pro-video-editor-5c91d.firebaseapp.com',
    storageBucket: 'pro-video-editor-5c91d.firebasestorage.app',
    measurementId: 'G-B1WZYMBZ8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiOF3lwOd-ZeoRn7LKaIU4BeR5010nSf4',
    appId: '1:259944737321:android:2a68e1aac5d738864bca38',
    messagingSenderId: '259944737321',
    projectId: 'pro-video-editor-5c91d',
    storageBucket: 'pro-video-editor-5c91d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR_Bi9p6xHdltXRBcbk7Eq0o7dHU_KX3c',
    appId: '1:259944737321:ios:240722ee31e6e8dc4bca38',
    messagingSenderId: '259944737321',
    projectId: 'pro-video-editor-5c91d',
    storageBucket: 'pro-video-editor-5c91d.firebasestorage.app',
    iosBundleId: 'ch.waio.proVideoEditorExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR_Bi9p6xHdltXRBcbk7Eq0o7dHU_KX3c',
    appId: '1:259944737321:ios:240722ee31e6e8dc4bca38',
    messagingSenderId: '259944737321',
    projectId: 'pro-video-editor-5c91d',
    storageBucket: 'pro-video-editor-5c91d.firebasestorage.app',
    iosBundleId: 'ch.waio.proVideoEditorExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs9shlH6BKBjV5kH7DbM6zGSJQN7Xr9go',
    appId: '1:259944737321:web:16b99047fbd7427b4bca38',
    messagingSenderId: '259944737321',
    projectId: 'pro-video-editor-5c91d',
    authDomain: 'pro-video-editor-5c91d.firebaseapp.com',
    storageBucket: 'pro-video-editor-5c91d.firebasestorage.app',
    measurementId: 'G-DDYPX7W427',
  );
}
